blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/likec4/likec4/discussions/new
    about: Request new feature
  - name: Ask a question, give feedback, share your project
    url: https://github.com/likec4/likec4/discussions
    about: Connect with other community members with GitHub discussions
  - name: Get help on Discord
    url: https://discord.gg/86ZSpjKAdA
    about: Get help from maintainers on Discord
