name: build

on: [push]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: build and test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Get yarn cache directory
        id: yarn-cachedir
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache/restore@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cachedir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Compile
        run: yarn turbo run compile

      - name: Test
        run: yarn vitest run

      - if: success() && steps.yarn-cache.outputs.cache-hit != 'true' && github.ref_protected == true
        uses: actions/cache/save@v3
        with:
          path: ${{ steps.yarn-cachedir.outputs.dir }}
          key: ${{ steps.yarn-cache.outputs.cache-primary-key }}
