name: e2e update screenshots

on:
  workflow_dispatch:

env:
  NODE_ENV: production
  CLOUDFLARE_ENV: "production"
  FORCE_COLOR: true
  DO_NOT_TRACK: "1"

permissions:
  pull-requests: write
  contents: write

jobs:
  update-screenshots:
    name: create pull request
    timeout-minutes: 15
    runs-on: ubuntu-24.04-arm
    steps:
      - name: bot token
        id: bot-token
        uses: ./.github/actions/bot-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key-base64: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          token: ${{ steps.bot-token.outputs.token }}
          ssh-strict: "no"

      - name: üõ†Ô∏è bootstrap
        uses: ./.github/actions/bootstrap

      - name: üì¶ pack
        run: |
          pnpm turbo run pack --filter='@likec4/core' --filter='likec4'

      - name: üõ†Ô∏è install e2e dependencies
        working-directory: e2e
        run: |
          pnpm install
          pnpm add ../packages/core/package.tgz ../packages/likec4/package.tgz
          pnpm install:chromium
          pnpm bootstrap

      - name: ‚öôÔ∏è update screenshots
        working-directory: e2e
        run: |
          pnpm test:update-screenshots

      - name: create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.bot-token.outputs.token }}
          commit-message: "chore: update e2e screenshots"
          title: "chore: update e2e screenshots"
          branch: update-screenshots/${{ github.ref_name }}
          add-paths: "e2e/tests/**"
          delete-branch: true

      - name: enable automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
