name: release
on:
  pull_request:
    types:
      - closed

env:
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: 'likec4'
  NODE_ENV: 'production'

jobs:
  ship:
    name: ship
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    permissions: write-all
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
          ref: develop

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          turborepo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build

      - name: Configure git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release
        run: yarn shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish VSCode extension
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo " version: $VERSION"
          yarn vsce publish $VERSION
        working-directory: packages/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
